version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4

workflows:
  verify:
    jobs:
      - orb-tools/lint:
          name: lint
      - orb-tools/pack:
          name: pack
          source-dir: src
          attach-workspace: true
      - orb-tools/publish:
          name: publish
          context: orb-publishing
          filters:
            branches:
              ignore: master
          checkout: false
          attach-workspace: true
          workspace-root: .
          orb-path: orb.yml
          orb-ref: entur/gcp-auth@dev:$CIRCLE_BRANCH
          requires:
            - pack
      - orb-tools/test-in-builds:
          name: test
          orb-location: orb.yml
          orb-name: gcp-auth
          attach-workspace: true
          context: dev
          checkout: true
          workspace-root: .
          test-steps: # these happen after the initial test-in-builds
            #- orb-tools/pack:
            #    source: src
            #    destination: orb.yml
            - orb-tools/local-test-build:
                test-config-location: test/install-test.yml
          requires:
            - publish
            - lint
      - orb-tools/increment:
          name: release
          context: orb-publishing
          filters:
            branches:
              only: master
          checkout: false
          attach-workspace: true
          orb-ref: entur/gcp-auth
          requires:
            - lint
            - pack
            - test
