description: |
  Demonstrate authenticating to gcp with this orb.

usage:
  version: 2.1

orbs:
  # Use volatile if you always want the newest version.
  gcp-auth: entur/gcp-auth@volatile

jobs:
  deploy-application:
    docker:
      # Comes with a lof of pre-installed features; including gcloud.
      - image: entur/cci-toolbox:3.0

    steps:
      - gcp-auth/authenticate-gcp:
          # If not provided, env variable GCLOUD_SERVICE_KEY is used
          gcp-service-key: "{'json':'here'}" # do not use plain text here!

workflows:
  version: 2.1

  my-workflow:
    jobs:
      - deploy-application:
          name: use-gcloud-cli-for-something
          # Choose a context with the appropriate env variables set
          context: a-context-that-contain-gcp-env and dockerhub credentials varialbes
